# 2) в папке config будут храниться только yaml файлики,
# которые хранят конфигурацию (как я понял, yaml используеться
# для конфигурации на докере)

# ОБНОВЛЕНИЕ. Я решил использовать json потому что yaml не парситься


# 3) приложению нужно знать в каком окружении его запускают, 
# оно должно понимать, что это локальная машина или это удаленный сервер,
# а если это удаленный сервер, то еще можна разделять на dev server и prod server
env: "local" # local, dev, prod 

# 4) пусть к файлу, в котором будет храниться бд,
# в нашем случае это sqlite
storage_path: "../../storage/storage.db"

# 5) конфигурируем сервер
http_server: 
  address: "localhost:8080"
  timeout: 4s # таймаут на обработку запроса (это время на чтение запроса и такое же время на отправку ответа)
  idle_timeout: 60s 
  # idle_timeout - это время жизни соиденения с клиентом, то есть сервер обычно оптимизирован таким образом, 
  # что если от одного клиента нам приходит несколько запросов, между которыми не очень много времени, 
  # то мы используем одно соиденение. Нет смысла каждый раз открывать закрывать соиденение на каждый 
  # запрос от одного клиента и мы будем переиспользовать одно и тоже соиденение, но если клиент нам 
  # долго не запрашивает, то такое соиденение нужно обрывать.    
  user: "123"
  password: "123"